### REGISTER
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Marwa",
  "email": "marwa@test.com",
  "password": "1234"
}

### LOGIN
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "marwa@test.com",
  "password": "1234"
}