-- MySQL Script generated by MySQL Workbench
-- Sun May  3 14:50:35 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_role` INT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `CreatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `id_role_idx` (`id_role` ASC) VISIBLE,
  CONSTRAINT `id_role`
    FOREIGN KEY (`id_role`)
    REFERENCES `mydb`.`Roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Restaurants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Restaurants` (
  `id` INT NULL AUTO_INCREMENT,
  `contact_person` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `phone` VARCHAR(45) NULL,
  `adddress` TEXT NULL,
  `latitude` DECIMAL(10,8) NULL,
  `longitude` DECIMAL(11,8) NULL,
  `opening_hours` JSON NULL,
  `CreatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Phone_UNIQUE` (`phone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OffersStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OffersStatus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Offers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Offers` (
  `id` INT NOT NULL,
  `id_restaurant` INT NOT NULL,
  `id_status` INT NULL,
  `title` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `original_price` INT NULL,
  `discounted_price` INT NULL,
  `available_quantity` INT NULL,
  `pickup_start` TIME NULL,
  `pickup_end` TIME NULL,
  `status_id` INT NULL,
  `CreatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `idRestaurants_idx` (`id_restaurant` ASC) VISIBLE,
  INDEX `id_status_idx` (`id_status` ASC) VISIBLE,
  CONSTRAINT `id_restaurant`
    FOREIGN KEY (`id_restaurant`)
    REFERENCES `mydb`.`Restaurants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_status`
    FOREIGN KEY (`id_status`)
    REFERENCES `mydb`.`OffersStatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrderStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrderStatus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_status` INT NULL,
  `total` INT NULL,
  `CreatedAt` TIMESTAMP NULL,
  INDEX `idUsers_idx` (`id_user` ASC, `id` ASC) VISIBLE,
  INDEX `id_status_idx` (`id_status` ASC) VISIBLE,
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user` , `id`)
    REFERENCES `mydb`.`Users` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_status`
    FOREIGN KEY (`id_status`)
    REFERENCES `mydb`.`OrderStatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Payements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Payements` (
  `idPayements` INT NOT NULL AUTO_INCREMENT,
  `idOrders` INT NOT NULL,
  `Method` ENUM('card', 'cash') NULL,
  `Amount` INT NULL,
  `Status` ENUM('successful', 'failed') NULL,
  `TransactionReference` VARCHAR(100) NULL,
  `CreatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`idPayements`),
  INDEX `idOrders_idx` (`idOrders` ASC) VISIBLE,
  CONSTRAINT `idOrders`
    FOREIGN KEY (`idOrders`)
    REFERENCES `mydb`.`Orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_order` INT NOT NULL,
  `rating` INT NULL,
  `comment` TEXT NULL,
  `CreatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `idUsers_idx` (`id_user` ASC) VISIBLE,
  INDEX `id_order_idx` (`id_order` ASC) VISIBLE,
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_order`
    FOREIGN KEY (`id_order`)
    REFERENCES `mydb`.`Orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Favorites` (
  `idUsers` INT NOT NULL,
  `idRestaurants` INT NOT NULL,
  INDEX `idRestaurants_idx` (`idRestaurants` ASC) VISIBLE,
  CONSTRAINT `idUsers`
    FOREIGN KEY (`idUsers`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idRestaurants`
    FOREIGN KEY (`idRestaurants`)
    REFERENCES `mydb`.`Restaurants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrderDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrderDetails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_order` INT NULL,
  `id_offer` INT NULL,
  `quantity` INT NULL DEFAULT 1,
  `total` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_order_idx` (`id_order` ASC) VISIBLE,
  INDEX `id_offer_idx` (`id_offer` ASC) VISIBLE,
  CONSTRAINT `id_order`
    FOREIGN KEY (`id_order`)
    REFERENCES `mydb`.`Orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_offer`
    FOREIGN KEY (`id_offer`)
    REFERENCES `mydb`.`Offers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Data for table `mydb`.`Roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Roles` (`id`, `name`) VALUES (DEFAULT, 'admin');
INSERT INTO `mydb`.`Roles` (`id`, `name`) VALUES (DEFAULT, 'customer');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`OffersStatus`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`OffersStatus` (`id`, `name`) VALUES (DEFAULT, 'available');
INSERT INTO `mydb`.`OffersStatus` (`id`, `name`) VALUES (DEFAULT, 'sold_out');
INSERT INTO `mydb`.`OffersStatus` (`id`, `name`) VALUES (DEFAULT, 'expired');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`OrderStatus`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`OrderStatus` (`id`, `name`) VALUES (DEFAULT, 'reserved');
INSERT INTO `mydb`.`OrderStatus` (`id`, `name`) VALUES (DEFAULT, 'collected');
INSERT INTO `mydb`.`OrderStatus` (`id`, `name`) VALUES (DEFAULT, 'paid');
INSERT INTO `mydb`.`OrderStatus` (`id`, `name`) VALUES (DEFAULT, 'cancelled');

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
